### ISSUE TITLE
Resource collection: natxet/CssMin mangles css function definitions (@-moz-document url-prefix())

### ISSUE THREAD

**Issue by UlrichKu** [chameleon-system/chameleon-system#51]
**Describe the bug**
If a css file has a (moz) function defintion and a media query with the same function afterwards this will result in one bracket too few after minification.

**Affected version(s)**
\>=6.1

**To Reproduce**
1. Add a css definition like this to a .css included in the page:
```css
@-moz-document url-prefix() {
  .btn { margin: 0 }
}
@media (max-width: 768px) {
  @-moz-document url-prefix() {
    .btn { margin: 5px; }
  }
}
```
2. Make sure parameter chameleon_system_core.resources.enable_external_resource_collection_minify: true
3. Delete and recreate the css resource collection in web/chameleon/outbox/static/css/
4. Inspect the resulting combined css file there will be one bracket unclosed

**Expected behavior**
Not sure what to do here as the broken part is a rather stale external project.

A possible workaround without this problem is to reformat the css and move the second (media) block somewhere else - ie after another css block.
